package campsiterentalsapp;
import java.util.*;
import java.io.FileWriter;
/**
 *
 * @author x19126468
 */
public class CampsiteGUI extends javax.swing.JFrame {
    private ArrayList <Bookings> bookingsList;
    public String name;
    public String electricity;
    public String bookingType;
    public int pitchNum;
    public int stayNum;
    public int adultsNum;
    public int childrenNum;

    
    public CampsiteGUI() {
        initComponents();
        bookingsList = new ArrayList <>();
        electricity = new String();
        bookingType = new String();
        name = new String();
        adultsNum = 0;
        childrenNum = 0;
        pitchNum = 0;
        stayNum = 0;        
    }
    
//Create and declare ArrayList Object
        /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        appTittle = new javax.swing.JLabel();
        nameLbl = new javax.swing.JLabel();
        pitchNumLbl = new javax.swing.JLabel();
        stayDurationLbl = new javax.swing.JLabel();
        adultsLbl = new javax.swing.JLabel();
        childrenLbl = new javax.swing.JLabel();
        electricityLbl = new javax.swing.JLabel();
        bookingTypeLbl = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        pitchNumTxt = new javax.swing.JTextField();
        stayDurationTxt = new javax.swing.JTextField();
        electricityTxt = new javax.swing.JTextField();
        adultsNumTxt = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        displayAllBtn = new javax.swing.JButton();
        saveAllBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayTxt = new javax.swing.JTextArea();
        childrenNumTxt = new javax.swing.JTextField();
        bookingTypeTxt = new javax.swing.JTextField();
        displayLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        appTittle.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        appTittle.setText("Campsite Rentals - Booking Details");

        nameLbl.setText("Full Name");

        pitchNumLbl.setText("Pitch Number");

        stayDurationLbl.setText("Stay Duration");

        adultsLbl.setText("Adults");

        childrenLbl.setText("Children");

        electricityLbl.setText("Electricity");

        bookingTypeLbl.setText("Booking Type");

        nameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTxtActionPerformed(evt);
            }
        });

        pitchNumTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pitchNumTxtActionPerformed(evt);
            }
        });

        stayDurationTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stayDurationTxtActionPerformed(evt);
            }
        });

        adultsNumTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adultsNumTxtActionPerformed(evt);
            }
        });

        addBtn.setText("Add Booking");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        deleteBtn.setText("Delete Booking");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        displayAllBtn.setText("Display All Bookings");
        displayAllBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayAllBtnActionPerformed(evt);
            }
        });

        saveAllBtn.setText("Save all to txt File");
        saveAllBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAllBtnActionPerformed(evt);
            }
        });

        displayTxt.setColumns(20);
        displayTxt.setRows(5);
        jScrollPane1.setViewportView(displayTxt);

        childrenNumTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                childrenNumTxtActionPerformed(evt);
            }
        });

        bookingTypeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingTypeTxtActionPerformed(evt);
            }
        });

        displayLbl.setText("Display:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(displayLbl)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(pitchNumLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pitchNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(electricityLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(electricityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(displayAllBtn)
                                        .addGap(37, 37, 37)
                                        .addComponent(saveAllBtn))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(72, 72, 72)
                                        .addComponent(adultsLbl)
                                        .addGap(18, 18, 18)
                                        .addComponent(adultsNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bookingTypeLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bookingTypeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(stayDurationLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(stayDurationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nameLbl)
                                .addGap(18, 18, 18)
                                .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(childrenLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(childrenNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28))))
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(appTittle)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(appTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLbl)
                    .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adultsLbl)
                    .addComponent(adultsNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(childrenNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(childrenLbl))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pitchNumLbl)
                    .addComponent(pitchNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(electricityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(electricityLbl)
                    .addComponent(bookingTypeLbl)
                    .addComponent(bookingTypeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stayDurationLbl)
                    .addComponent(stayDurationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(displayLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn)
                    .addComponent(deleteBtn)
                    .addComponent(displayAllBtn)
                    .addComponent(saveAllBtn))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTxtActionPerformed

    private void pitchNumTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pitchNumTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pitchNumTxtActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        
        //Retrieve from txt field
        name = nameTxt.getText();
        bookingType = bookingTypeTxt.getText();
        electricity = electricityTxt.getText(); 
        pitchNum = Integer.parseInt(pitchNumTxt.getText());
        stayNum = Integer.parseInt(stayDurationTxt.getText());
        adultsNum = Integer.parseInt(adultsNumTxt.getText());
        childrenNum = Integer.parseInt(childrenNumTxt.getText());
        
        //Booking object
        Bookings b = new Bookings();
        b.setName(name);
        b.setBookingType(bookingType);
        b.setElectricity(electricity);
        b.setPitchNum (pitchNum);
        b.setStayNum (stayNum);
        b.setAdultsNum(adultsNum);
        b.setChildrenNum(childrenNum);
            
        //Add object to Arraylist
        bookingsList.add(b);
        
        //Print Booking added
        displayTxt.append("Booking Added "+ "For " + name +" ");
        displayTxt.append("\n");
    }//GEN-LAST:event_addBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        //Retrieve from txt field
        name = nameTxt.getText();
        bookingType = bookingTypeTxt.getText();
        electricity = electricityTxt.getText(); 
        pitchNum = Integer.parseInt(pitchNumTxt.getText());
        stayNum = Integer.parseInt(stayDurationTxt.getText());
        adultsNum = Integer.parseInt(adultsNumTxt.getText());
        childrenNum = Integer.parseInt(childrenNumTxt.getText());
        
        //Booking object
        Bookings b = new Bookings();
        b.setName(name);
        b.setBookingType(bookingType);
        b.setElectricity(electricity);
        b.setPitchNum (pitchNum);
        b.setStayNum (stayNum);
        b.setAdultsNum(adultsNum);
        b.setChildrenNum(childrenNum);
        
        //Delete last added Object (if Array is not empty)
        if (bookingsList.size()!=0){
            bookingsList.remove(b);
            displayTxt.append("Booking Removed "+ "Name " + name +" ");
            displayTxt.append("\n");
        }
        
        
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void saveAllBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAllBtnActionPerformed
        // TODO add your handling code here:
        //Save ArrayList to Txt File using File Writer

    }//GEN-LAST:event_saveAllBtnActionPerformed

    private void childrenNumTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_childrenNumTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_childrenNumTxtActionPerformed

    private void bookingTypeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingTypeTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookingTypeTxtActionPerformed

    private void stayDurationTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stayDurationTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stayDurationTxtActionPerformed

    private void adultsNumTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adultsNumTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adultsNumTxtActionPerformed

    private void displayAllBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayAllBtnActionPerformed

        //Loop array to print bookings
        for(int i = 0; i < bookingsList.size(); i++){
            displayTxt.append("List of Bookings: " + "Name = " + name + " Electricity = " + electricity + " Pitch Number = " + pitchNum + " Stay in Nitghs = " + stayNum + " Booking Type = " + bookingType + " Adults = " + adultsNum + " Children = " + childrenNum);
            displayTxt.append("\n");
        }
    }//GEN-LAST:event_displayAllBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CampsiteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CampsiteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CampsiteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CampsiteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CampsiteGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JLabel adultsLbl;
    private javax.swing.JTextField adultsNumTxt;
    private javax.swing.JLabel appTittle;
    private javax.swing.JLabel bookingTypeLbl;
    private javax.swing.JTextField bookingTypeTxt;
    private javax.swing.JLabel childrenLbl;
    private javax.swing.JTextField childrenNumTxt;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton displayAllBtn;
    private javax.swing.JLabel displayLbl;
    private javax.swing.JTextArea displayTxt;
    private javax.swing.JLabel electricityLbl;
    private javax.swing.JTextField electricityTxt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JLabel pitchNumLbl;
    private javax.swing.JTextField pitchNumTxt;
    private javax.swing.JButton saveAllBtn;
    private javax.swing.JLabel stayDurationLbl;
    private javax.swing.JTextField stayDurationTxt;
    // End of variables declaration//GEN-END:variables
}
